package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Nodefaultkey'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Nodefaultkey")
    name = "nodefaultkey"
    url = "dfg"
    authMethod = password {
        userName = "AChubatova"
        password = "credentialsJSON:319b71ec-dc0e-4e35-a192-4907fdfbdcad"
    }
}))

