package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Password2custom'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Password2custom")
    name = "password2_custom"
    url = "sdfsdf"
    authMethod = password {
        userName = "sdff"
        password = "credentialsJSON:da9fde61-25dd-47e7-8532-b465191e70be"
    }
}))

