package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Password3againwithoutcustom'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Password3againwithoutcustom")
    name = "password3_againwithoutcustom"
    url = "sfdf"
    authMethod = password {
        userName = "sdf"
        password = "credentialsJSON:77c49882-38a2-43f2-9b9e-68f9e8b50b89"
    }
}))

